import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import Footer from "./_Components/Footer/Footer";
import FirstNav from "./_Components/FirstNav/FirstNav";
import { Toaster } from "@/components/ui/sonner";
import MyProvider from "./_Components/MyProvider/MyProvider";
import CartContextProvider from "@/context/CartContext";
import WishlistContextProvider from "@/context/WishListContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <MyProvider>
          <CartContextProvider>
            <WishlistContextProvider>
              <Navbar />
              {children}
              <Toaster />
              <Footer />
            </WishlistContextProvider>
          </CartContextProvider>
        </MyProvider>
      </body>
    </html>
  );
}
